fix: fix expected multibase encoding format
w3c-ccg/data-integrity-test-suite-assertion pull request #28
Opened 2024-03-04 18:04 UTC by tminard

Specs differ on the expected multibase encoding for `proof.proofValue`. This PR updates the assertion to use the expected assertion.

2024-03-04 18:13 UTC, tminard commented on index.js
> +      });
This simple assert doesn't expose _which_ expected format. I'd like to do that for clarity, but interestingly the original assertion is using "some", so it isn't clear how to do this. I can expose the expected encoding in the assertion message

2024-03-04 18:41 UTC, tminard commented on helpers.js
> +const BASE_64URL_REGEX = /^[A-Za-z0-9\-_=]+$/;
I'll check this against the published spec. Note the pad `=` in there, which I dont think is technically on base64url, but ill double-check

2024-03-04 19:09 UTC, BigBlueHat requested changes

2024-03-04 19:09 UTC, BigBlueHat commented on index.js
> +            shouldBeBase64Url(proofValue) : shouldBeBs58(proofValue);
Looks like `bbs-2023` also differs.

I'd stick with the prevailing pattern on naming...at least for now. It's used in the specs as well (whereas a constant used in this app would not be...and would result in fewer search results for someone learning).

2024-03-04 20:32 UTC, tminard commented on index.js
> +            shouldBeBase64Url(proofValue) : shouldBeBs58(proofValue);
Fixed. I ran a test in the associated bbs suite and it passed when previously failing.

2024-03-05 17:14 UTC, BigBlueHat requested changes
Commit messages should follow https://github.com/digitalbazaar/bedrock/blob/main/CONTRIBUTING.md#commit-messages 

Otherwise, everything else looks fine!

2024-03-05 17:42 UTC, BigBlueHat approved these changes
Thanks!

2024-03-05 17:43 UTC, merged