Update proofValue test title & assertions.
w3c-ccg/data-integrity-test-suite-assertion pull request #85
Opened 2024-07-22 19:26 UTC by aljones15

wording of this statement might be changed shortly.

2024-08-01 19:20 UTC, PatStLouis requested changes
Most of my comments are around these tests expecting proofs will always have a cryptosuite

2024-08-05 19:03 UTC, BigBlueHat commented on suites/create.js
> +        shouldHaveProofValue({proof, expectedPrefix, encodingName});
@PatStLouis why remove this one?

2024-08-05 19:52 UTC, aljones15 commented on suites/create.js
> +          shouldHaveProofValue({proof, expectedPrefix, encodingName});
this actually already works with `Ed25519` https://github.com/w3c-ccg/data-integrity-test-suite-assertion/blob/3c53b6cf1e4db963c9ca5aa65b04e86000e65d8e/assertions.js#L41-L55

ed25519 is abs58 encoded.

https://www.w3.org/TR/vc-di-eddsa/#ed25519signature2020-0

2024-08-05 19:58 UTC, aljones15 commented on suites/create.js
>          } = expectedMultibasePrefix(proof.cryptosuite);
this works with DataIntegrity or Ed25519Signature2020.

2024-08-05 20:11 UTC, aljones15 commented on suites/create.js
> +          'Expected proof to have property "cryptosuite".');
this test is about proofValue so I just removed the cryptosuite check entirely: https://github.com/w3c-ccg/data-integrity-test-suite-assertion/pull/85/commits/a681268a0e7a6bab4621e2644fe8f5cab477b06a

2024-08-05 20:21 UTC, PatStLouis commented on suites/create.js
> +          shouldHaveProofValue({proof, expectedPrefix, encodingName});
The issue is that `Ed25519Signature2020` doesn't use the `cryptosuite` field. [This section of the spec](https://www.w3.org/TR/vc-data-integrity/#dataintegrityproof), which the statement is from, is about `DataIntegrityProof` type, which `Ed25519Signature2020` isn't (it's `Ed25519Signature2020` type). I would expect the statements in the `DataIntegrityProof` suite section to only apply to proofs of type `DataIntegrityProof`.

2024-08-05 20:35 UTC, PatStLouis commented on suites/create.js
> +        shouldHaveProofValue({proof, expectedPrefix, encodingName});
It's not been removed, it's been moved, see line 225 in the edit right above this one

2024-08-05 21:09 UTC, aljones15 commented on suites/create.js
> +          shouldHaveProofValue({proof, expectedPrefix, encodingName});
addressed here: https://github.com/w3c-ccg/data-integrity-test-suite-assertion/pull/85/commits/d107aaf9958f324a04870972844da198d92ebc22

this is actually a problem in general for instance with the SD suites, some assertions are base proof only and some are derived proof only.

2024-08-06 12:36 UTC, PatStLouis approved these changes
I'm happy with these changes!

2024-08-06 21:26 UTC, merged